services:
  # 1) etcd as MetaStore
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: milvus-etcd
    command:
      - etcd
      - --name=s1
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://milvus-etcd:2379
    environment:
      endpoints: "milvus-etcd:2379"
      enableAuth: false
    ports:
      - "2379:2379"
    networks:
      - chatbot-network
    restart: unless-stopped

  # 2) MinIO as Object Storage
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - chatbot-network
    restart: unless-stopped

  # 3) Milvus Standalone
  milvus-standalone:
    image: milvusdb/milvus:v2.5.10
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: "milvus-etcd:2379"
      MINIO_ADDRESS: "milvus-minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio
    networks:
      - chatbot-network
    restart: unless-stopped

  # 4) Streamlit Chatbot App (inkl. Embedding-Modell lokal)
  chatbot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empathic-chatbot
    ports:
      - "8501:8501"
    environment:
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
    volumes:
      - ./docs:/empathic-conversational-agent-lab/docs
      - ./data:/empathic-conversational-agent-lab/data
      - ./.streamlit:/home/app/.streamlit
    depends_on:
      - milvus-standalone
    networks:
      - chatbot-network
    restart: unless-stopped

# 5) Reverse-proxy for HTTP/HTTPS
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - chatbot-app
    networks:
      - chatbot-network
    restart: unless-stopped

networks:
  chatbot-network:
    driver: bridge

volumes:
  minio_data:
  milvus_data:
