name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics


  docker-build:
    needs: basic-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t empathic-chatbot:latest .
        echo "Docker build completed"

  deploy:
    needs: docker-build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy on VM
      - run: |
         cd /opt/streamlit-stack
         git fetch origin main
         git reset --hard origin/main
         docker compose build --no-cache
         docker compose up -d
